### ISSUE TITLE
Cat form flags you for hacking

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#132] opened 2015-06-13 02:32 UTC
Going into cat form currently bans you from the server by the anti hack system.

**Comment by AsuraDev** [comment] 2015-06-13 07:48
Confirmed. Due to server-side check to ensure players don't have flags their not supposed to.

**Comment by AsuraDev** [comment] 2015-06-14 08:54
Fixed. Will be in the update on monday.

**Closed by AsuraDev** 2015-06-14 08:54 UTC
Labels: Core.Misc.Other, Status.Fixed
