### ISSUE TITLE
Casting Battle Shout will flag for PvP

### ISSUE THREAD

**Issue by rzeg** [Crestfall/JadefireTracker#5] opened 2015-06-07 20:40 UTC
Casting Battle Shout as a warrior will flag you for PvP. Not sure if this affects other AoE buffs

**Comment by AsuraDev** [comment] 2015-06-10 06:11
I just tested this on a brand new Warrior. Was not flagged on it or my 60 test warrior. Did you have a party member nearby who was flagged for PvP? I don't see this happening otherwise, and I'm not sure if that should be intended or not since most times buffing/healing a PvP enabled target will flag you as well.

More details are required.

**Comment by AsuraDev** [comment] 2015-08-04 12:02
Closing because this still can't be reproduced.

**Closed by AsuraDev** 2015-08-04 12:02 UTC
Labels: PlayerClass.Warrior, Status.NeedsInfo
