### ISSUE TITLE
Guild tabard on character select broken

### ISSUE THREAD

**Issue by Daribon** [Crestfall/JadefireTracker#395] opened 2015-08-15 02:52 UTC
At the character select screen your guild tabard will always be shown as grey, even if you are inside a guild.

**Comment by AsuraDev** [comment] 2015-10-05 15:51
Closing this as locally, I can't reproduce this. Perhaps I fixed it and didn't notice it. If it's found after the update, just reopen this.

**Closed by AsuraDev** 2015-10-05 15:51 UTC
Labels: Core.Misc.Other, Status.Rejected
